import Head from 'next/head'
import CollectionList from '../components/CollectionList';
import Image from 'next/image';
import ChickenWrap from '../images/chick-wrap.png';
import Fork from '../images/fork.png';
import Link from 'next/link';
import { useEffect } from 'react';

export default function Home() {
  const createCart = async () => {
    let localCartData = JSON.parse(window.localStorage.getItem('Weight-Plate:cart'));
    if (localCartData) {
      return;
    }

    localCartData = await fetch('/api/create-cart')
      .then((res) => res.json())
      .catch((err) => console.error(err));
    window.localStorage.setItem(
      'Weight-Plate:cart',
      JSON.stringify(localCartData)
    )
  }
  useEffect(() => {
    createCart();

  }, [])

  return (
    <>
      <Head>
        <title>Weight Plate</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      {/* Hero Section */}
      <div className='w-full text-center flex justify-center items-center h-screen bg-white'>
        <div className='w-full h-full px-8 flex flex-col justify-evenly'>

          <h1 className='title'>
            Just finished a workout?
          </h1>

          <h2 className='subTitle'>
            Weight Plate has got you covered! Visit us for an ideal post-workout meal.
            Or if you have not worked out today, come get your pre-workout meal.
          </h2>

          <Link href={'/order'}>
            <button className='mx-auto my-0 button'>
              Find Your Weight Plate
            </button>
          </Link>
        </div>

        <div className='w-full h-full relative'>
          <Image
            src={ChickenWrap}
            fill
            alt='Chicken Wrap'
          />
        </div>
      </div>
      {/* End of Hero Section */}

      {/* Protein Powder Section */}
      <div className='w-full h-screen bg-white relative flex justify-end flex-row mobile:flex-col mobile:justify-center'>
        <div className='protein mobile:clip-none mobile:h-1/2 w-full'></div>

        <div className='w-full flex flex-col justify-start items-end gap-10 mobile:items-center mobile:z-20'>
          <h1 className='title'>
            Tasty & Optimal Protein
          </h1>
          <h2 className='subTitle'>
            Our protein proves to be the most efficient for your fitness goals
          </h2>

          <h3 className='subTitle underline'>
            30g protein in only 150 calories
          </h3>
        </div>

      </div>
      {/* End of Protein Powder Section */}

      {/* Fork Section */}
      <div className='diagonal-color-background w-full h-screen bg-white relative flex justify-between flex-row mobile:flex-col'>
        <div className='flex flex-col w-full h-1/2 justify-start gap-10'>
          <h1 className='title text-left'>
            Helping you pick up the fork
          </h1>
          <h1 className='subTitle text-center'>
            Or put it down
          </h1>

          <h1 className='subTitle text-center'>
            Depending on your goals
          </h1>

          <Link href={'/menu'} className='mx-auto my-0'>
            <button className='button mx-auto my-0 '>
              View Menu
            </button>
          </Link>

        </div>

        <div className='w-full h-full relative'>
          <Image
            src={Fork}
            fill
            alt='Chicken Wrap'
          />
        </div>
      </div>
      {/* End of Fork Section */}

      {/* Category Section */}
      <CollectionList />
      {/* End of Category Section */}
    </>
  )
}
