import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import AddToCart from '../components/Add-To-Cart';
import Cart from '../components/Cart';
import styles from '../styles/Home.module.css'

export async function getStaticProps() {
  const url = new URL('http://localhost:3000');
  url.pathname = '/api/products';

  const res = await fetch(url.toString());

  if (!res.ok) {
    console.error(res);
    return { props: {} };
  }

  const results = await res.json();

  const products = results.data.products.edges.map(({ node }) => {
    return {
      id: node.id,
      title: node.title,
      description: node.description,
      imgSrc: node.images.edges[0].node.src,
      imgAlt: node.title,
      price: node.variants.edges[0].node.priceV2.amount,
      slug: node.handle
    }
  });

  return {
    props: { products }
  };
};

function Product({ product }) {
  const formattedPrice = new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD'
  });
  return (
    <div className={styles.product}>
      <Link href={`/product/${product.slug}`}>
        <Image
          width={100}
          height={100}
          src={product.imgSrc}
          alt={product.imgAlt}
        />
      </Link>

      <h2>
        {product.title}
      </h2>

      <p>
        {product.description}
      </p>

      <p className={styles.price}>
        {formattedPrice.format(product.price)}
      </p>
    </div>
  )
}

export default function Home({ products }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Weight Plate</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Store
        </h1>

        <div className={styles.products}>
          {products.map((product) =>
          (
            <Product
              key={product.id}
              product={product} />
          )
          )}
        </div>

        <Cart />
      </main>
    </div>
  )
}
