import Head from 'next/head'
import Cart from '../components/Cart';
import CollectionList from '../components/CollectionList';
import Header from '../components/Header';
import ProductList from '../components/ProductList';
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Weight Plate</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <Header />
        <ProductList />
        <CollectionList />
        <Cart />
      </main>
    </div>
  )
}
